import AuthProvider from "@/components/AuthProvider";
import AuthListener from "@/components/AuthListener";
import { createServerClient } from "@/utils/supabase-server";
import "./globals.css";

export const revalidate = 0;

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default async function RootLayout({ children }) {
  const supabase = createServerClient();
  const {
    data: { session }
  } = await supabase.auth.getSession();

  return (
    <html lang="en">
      <body>
        <AuthProvider session={session}>
          <AuthListener serverAccessToken={session?.access_token} />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
